from typing import Protocol, Type

from shinshi.abc.services.iservice import IService


class IKernel(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def run(self) -> None: ...

    def get_service[T](self, service_interface: Type[T]) -> T: ...

    def register_service(self, service_interface: Type, service: IService) -> None: ...

    def remove_service(self, service_interface: Type) -> None: ...
