version: '3.8'

volumes:
  database:
  redis:

networks:
  default:

services:

  discord:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    networks:
      - default
    env_file: secrets/app.env

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - default
    env_file: secrets/database.env

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data
