version: 1
disable_existing_loggers: false

root:
  level: INFO
  handlers: [console, file]

formatters:
  internal:
    format: "%(asctime)s - %(levelname)s - %(filename)s:%(funcName)s:%(lineno)d - %(name)s - %(message)s"
  external:
    (): colorlog.ColoredFormatter
    format: "%(thin)s%(asctime)s%(reset)s %(bold_black)s[%(log_color)s%(levelname)s%(bold_black)s] [%(filename)s:%(funcName)s:%(lineno)d] [%(cyan)s%(name)s%(bold_black)s]%(reset)s %(message)s"
    log_colors:
      DEBUG: purple
      INFO: black
      WARNING: yellow
      ERROR: red
      CRITICAL: white,bg_red

handlers:
  console:
    class: logging.StreamHandler
    formatter: external
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: internal
    filename: logs/shinshi.log
    maxBytes: 1024
    backupCount: 3
