version: 1
disable_existing_loggers: false

root:
  level: DEBUG
  handlers: [console]

formatters:
  internal:
    format: "%(asctime)s - %(levelname)s - %(filename)s:%(funcName)s:%(lineno)d - %(name)s - %(message)s"
  external:
    (): colorlog.ColoredFormatter
    format: "%(thin)s[%(asctime)s%(reset)s %(bold)s%(log_color)s%(levelname)-1.1s%(reset)s%(thin)s] [%(filename)s:%(funcName)s:%(lineno)d] [%(cyan)s%(name)s%(reset)s%(thin)s]:%(reset)s %(message)s"
    datefmt: "%H:%M:%S %Y-%m-%d"
    log_colors:
      DEBUG: purple
      INFO: cyan
      WARNING: yellow
      ERROR: red
      CRITICAL: white,bg_red

handlers:
  console:
    class: logging.StreamHandler
    formatter: external
    stream: ext://sys.stdout
