version: '3.8'

volumes:
  database:
  redis:

networks:
  default:

services:
  shinshi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - database
    networks:
      - default
    env_file: ../app.env

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - default
    env_file: ../database.env
