from os import PathLike
from typing import Any, Dict, Protocol


class IConfigurationService(Protocol):
    def setup_logging(self) -> None: ...

    def load_dotenv(self) -> None: ...

    def get_config(self, name: str) -> Dict[str, Any] | None: ...

    def load_config(self, config_path: PathLike[str]) -> Dict[str, Any] | None: ...
